#!/usr/bin/env bash
#
# Install this as a git pre-commit hook:
# ln -sf ../../.githooks/pre-commit .git/hooks/pre-commit

set -euxo pipefail

typos

mapfile -t staged_files < <(git diff --cached --name-only --diff-filter=ACMR)

if [[ ${#staged_files[@]} -gt 0 ]]; then
	pnpm exec prettier --write --ignore-unknown "${staged_files[@]}"
	git add -- "${staged_files[@]}"
fi
