/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as UiPlaygroundRouteImport } from './routes/ui/playground';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const UiPlaygroundRoute = UiPlaygroundRouteImport.update({
  id: '/ui/playground',
  path: '/ui/playground',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/ui/playground': typeof UiPlaygroundRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/ui/playground': typeof UiPlaygroundRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/ui/playground': typeof UiPlaygroundRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/ui/playground';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/ui/playground';
  id: '__root__' | '/' | '/ui/playground';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  UiPlaygroundRoute: typeof UiPlaygroundRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ui/playground': {
      id: '/ui/playground';
      path: '/ui/playground';
      fullPath: '/ui/playground';
      preLoaderRoute: typeof UiPlaygroundRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiPlaygroundRoute: UiPlaygroundRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
